import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{parseHTML}=require(process.env.LINKEDOM_PATH||'linkedom');
const root=new URL('../docs/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8');const storage=new Map();const tick=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));};
async function boot(exam,loaded=true){const data=JSON.parse(fs.readFileSync(new URL(`exam-${exam}.json`,root)));const {window,document}=parseHTML(html);window.HTMLElement.prototype.focus=function(){};Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){const o=this.querySelector('option[selected]')||this.querySelector('option');return this._value??o?.getAttribute('value')??o?.textContent??''},set(v){this._value=String(v)}});const dialog=document.querySelector('dialog');dialog.showModal=()=>{dialog.open=true};dialog.close=()=>{dialog.open=false};
const key=exam===1?'mse250-study-v1':`mse250-exam-${exam}-v1`;const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
const ctx=vm.createContext({document,window,navigator:{},location:{search:`?exam=${exam}`,href:''},URLSearchParams,console,innerWidth:1280,localStorage,Blob,URL,crypto:globalThis.crypto,structuredClone,setTimeout,clearTimeout,fetch:async()=>({json:async()=>structuredClone(data)})});
const mods=new Map();async function get(name){if(mods.has(name))return mods.get(name);const code=name==='pdf-source.js'?`export async function loadPDF(){};export async function renderRegion(el,regions){el.textContent='PDF region book '+regions[0].book;return el.textContent};export async function regionText(){return 'PDF region'};export async function storedPDF(){return ${loaded?'new ArrayBuffer(1)':'undefined'}};export function clearPDF(){}`:fs.readFileSync(new URL(name,root),'utf8');const m=new vm.SourceTextModule(code,{context:ctx,identifier:name});mods.set(name,m);await m.link(spec=>get(spec.replace('./','')));return m;}const m=await get('app.js');await m.evaluate();await tick();return {data,document,ctx,key,click:async(sel)=>{const el=document.querySelector(sel);assert.ok(el,`Missing ${sel} exam ${exam}: ${document.querySelector('main').textContent.slice(0,500)}`);assert.ok(!el.disabled,`Disabled ${sel}`);el.click();await tick();},state:()=>JSON.parse(storage.get(key))};}
const expected=[300,240,300,320,320];
for(let e=1;e<=5;e++){
 let ui=await boot(e),q=ui.data.questions;assert.equal(q.length,expected[e-1]);assert.equal(new Set(q.map(x=>x.id)).size,q.length);assert.ok(ui.document.querySelector('h1').textContent.includes(`of ${q.length}`));
 await ui.click('[data-option="0"]');assert.equal(ui.document.querySelector('#feedback'),null);assert.equal(Object.keys(ui.state().active.answers).length,0);await ui.click('#hint');await ui.click('#submit');assert.equal(Object.keys(ui.state().active.answers).length,1);assert.equal(ui.state().active.cursor,0);await ui.click('#bookmark');await ui.click('#next');await ui.click('#skip');await ui.click('#shuffle');const order=ui.state().active.order;ui=await boot(e);assert.deepEqual(ui.state().active.order,order);assert.equal(ui.state().active.skipped.length,1);assert.equal(ui.state().bookmarks.length,1);
 await ui.click('#choose');assert.equal(ui.document.querySelectorAll('input[name=set]').length,ui.data.sets.length);await ui.click('#closeModal');await ui.click('#results');await ui.click('#restartAll');await ui.click('#confirmAction');
 for(let i=0;i<q.length;i++){assert.ok(ui.document.querySelector('h1').textContent.includes(`Question ${i+1} of ${q.length}`));await ui.click('[data-option="0"]');await ui.click('#submit');assert.ok(ui.document.querySelector('#feedback'));assert.equal(ui.state().active.cursor,i);await ui.click('#next');}
 assert.ok(ui.document.querySelector('.report'));assert.equal(Object.keys(ui.state().active.answers).length,q.length);assert.ok(ui.state().active.completedAt);assert.equal(ui.document.querySelectorAll('.tablewrap').length,4);const full=JSON.stringify(ui.state().active.answers);await ui.click('#retryIncorrect');await ui.click('#confirmAction');assert.equal(JSON.stringify(ui.state().history.at(-1).answers),full);await ui.click('[data-option="0"]');await ui.click('#submit');assert.equal(JSON.stringify(ui.state().history.at(-1).answers),full);
 console.log(`PASS Exam ${e}: ${q.length} UI submissions, source scope, explicit feedback, hints, bookmarks, skips, stable shuffle, ${ui.data.sets.length} sets, report and independent retry history.`);
}
const snapshots=[...storage];let ui=await boot(2);await ui.click('#reset');await ui.click('#eraseAll');await ui.click('#cancelAction');assert.deepEqual([...storage],snapshots);await ui.click('#reset');await ui.click('#eraseAll');await ui.click('#confirmAction');for(const [key,value] of snapshots)if(key!==ui.key)assert.equal(storage.get(key),value);assert.equal(ui.state().history.length,0);console.log('PASS: confirmed reset is isolated to selected exam; other exams unchanged.');
ui=await boot(5,false);assert.ok(ui.document.querySelector('.warning').textContent.includes('80'));assert.equal(ui.document.querySelectorAll('input[data-book]').length,5);assert.ok(ui.document.querySelector('#beginAvailable').disabled);console.log('PASS: final source gap visible; all five source books selectable; study blocked until a book is selected.');

await ui.click("#reset");await ui.click("#eraseEveryExam");await ui.click("#cancelAction");assert.ok(storage.size>1);await ui.click("#reset");await ui.click("#eraseEveryExam");await ui.click("#confirmAction");assert.equal(storage.size,1);assert.equal(ui.state().history.length,0);console.log("PASS: global reset confirms and erases all five exams.");
