// Pure study-state functions. Every response is immutable within an attempt.
export const STORAGE_KEY = 'mse250-study-v1';
export function blankState(){return {version:1,revision:0,active:null,history:[],bookmarks:[],textView:false};}
export function shuffle(items,rng=Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function newAttempt(ids,label='All 300 · source order',mixed=false){if(!ids.length||new Set(ids).size!==ids.length)throw Error('Choose a nonempty collection of unique questions.');return {id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,label,startedAt:new Date().toISOString(),completedAt:null,order:mixed?shuffle(ids):[...ids],answers:{},hints:{},skipped:[],drafts:{},cursor:0};}
export function archiveAndStart(state,ids,label,mixed=false){if(state.active)state.history.push(structuredClone(state.active));state.active=newAttempt(ids,label,mixed);return state.active;}
export function submit(attempt,q,choice){if(attempt.answers[q.id])throw Error('This answer is already recorded. Start a new attempt to retry.');if(!attempt.order.includes(q.id)||!Number.isInteger(choice)||choice<0||choice>=q.optionLabels.length)throw Error('Choose an available answer.');attempt.answers[q.id]={choice,correct:q.accepted.length?q.accepted.includes(choice):null,bookCorrect:q.bookKey===null?null:choice===q.bookKey,hint:!!attempt.hints[q.id],submittedAt:new Date().toISOString()};delete attempt.drafts[q.id];attempt.skipped=attempt.skipped.filter(id=>id!==q.id);if(attempt.order.every(id=>attempt.answers[id]))attempt.completedAt=new Date().toISOString();return attempt.answers[q.id];}
export function shuffleUnanswered(attempt,rng=Math.random){const current=attempt.order[attempt.cursor];const waiting=shuffle(attempt.order.filter(id=>!attempt.answers[id]),rng);let n=0;attempt.order=attempt.order.map(id=>attempt.answers[id]?id:waiting[n++]);attempt.cursor=attempt.order.indexOf(current);}
export function nextUnanswered(attempt){for(let n=1;n<=attempt.order.length;n++){const i=(attempt.cursor+n)%attempt.order.length;if(!attempt.answers[attempt.order[i]])return i;}return -1;}
export function skip(attempt,id){if(!attempt.answers[id]&&!attempt.skipped.includes(id))attempt.skipped.push(id);const i=nextUnanswered(attempt);if(i>=0)attempt.cursor=i;}
export function summary(attempt,questions,ids=attempt.order){const m=new Map(questions.map(q=>[q.id,q]));const s={total:ids.length,answered:0,graded:0,correct:0,withHint:0,withoutHint:0,hintUsed:0,ungraded:0,bookGraded:0,bookCorrect:0,incorrect:[],hintCorrect:[],cleanCorrect:[]};for(const id of ids){const q=m.get(id),a=attempt.answers[id];if(!q||!a)continue;s.answered++;if(a.hint)s.hintUsed++;if(a.bookCorrect!==null){s.bookGraded++;if(a.bookCorrect)s.bookCorrect++;}if(a.correct===null){s.ungraded++;continue;}s.graded++;if(a.correct){s.correct++;if(a.hint){s.withHint++;s.hintCorrect.push(id);}else{s.withoutHint++;s.cleanCorrect.push(id);}}else s.incorrect.push(id);}s.accuracy=s.graded?s.correct/s.graded:null;s.independent=s.graded?s.withoutHint/s.graded:null;return s;}
export function groups(attempt,questions,field){const m=new Map();for(const q of questions){if(!attempt.order.includes(q.id))continue;const key=field==='set'?`Ch ${q.chapter} · Set ${q.set}`:field==='chapter'?`Chapter ${q.chapter}`:q.topic;if(!m.has(key))m.set(key,[]);m.get(key).push(q.id);}return [...m].map(([name,ids])=>({name,ids,...summary(attempt,questions,ids)}));}
export function weakGroups(attempt,questions,field='set'){return groups(attempt,questions,field).filter(g=>g.graded>0&&(g.accuracy<.9||g.withHint>0)).sort((a,b)=>(a.independent-b.independent)||(b.graded-a.graded));}
export function validateState(s,questions){if(s?.version!==1||!Array.isArray(s.history)||!Array.isArray(s.bookmarks))throw Error('Saved progress has an unsupported format.');const map=new Map(questions.map(q=>[q.id,q]));for(const a of [...s.history,s.active].filter(Boolean)){if(!Array.isArray(a.order)||!a.order.length||a.order.some(id=>!map.has(id))||new Set(a.order).size!==a.order.length)throw Error('Saved question order is invalid.');if(!Number.isInteger(a.cursor)||a.cursor<0||a.cursor>=a.order.length||!a.answers||!a.hints||!Array.isArray(a.skipped)||!a.drafts)throw Error('Saved attempt fields are invalid.');for(const [id,r]of Object.entries(a.answers)){if(!a.order.includes(id)||!Number.isInteger(r.choice)||r.choice<0||r.choice>=map.get(id).optionLabels.length)throw Error('Saved answer is invalid.');const q=map.get(id);const correct=q.accepted.length?q.accepted.includes(r.choice):null;if(r.correct!==correct)throw Error('Saved score does not match the answer key.');}}return s;}
