import {sha256} from './sha256.js';
import * as pdfjs from './vendor/pdf.mjs';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;
const ligatures={'0.557129':'ti','0.634277':'tt','0.615723':'ft','0.855957':'tt'};
const pageCache=new Map(),textCache=new Map();const documents=new Map();
export async function loadPDF(bytes,metadata){const hash=globalThis.crypto?.subtle?[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join(''):sha256(bytes);if(hash!==metadata.sha256)throw Error(`This PDF does not match ${metadata.sourceFile}. Select the original ${metadata.pdfPages}-page project file; a modified edition has different page mappings.`);const documentPDF=await pdfjs.getDocument({data:new Uint8Array(bytes.slice(0)),isEvalSupported:false,useSystemFonts:true}).promise;if(documentPDF.numPages!==metadata.pdfPages)throw Error('The PDF page count differs from the mapped edition.');documents.set(metadata.book,documentPDF);pageCache.clear();textCache.clear();return documentPDF;}
async function getPage(n,book=1){const pdf=documents.get(book);if(!pdf)throw Error(`Choose Book ${book} first.`);const key=book+':'+n;if(!pageCache.has(key))pageCache.set(key,pdf.getPage(n));return pageCache.get(key);}
async function itemsFor(n,book=1){const key=book+':'+n;if(!textCache.has(key))textCache.set(key,(async()=>{const p=await getPage(n,book);return {items:(await p.getTextContent()).items,viewport:p.getViewport({scale:1})};})());return textCache.get(key);}
export async function regionText(regions){let result=[];for(const r of regions){const {items,viewport}=await itemsFor(r.page,r.book);const parts=items.filter(i=>{if(!i.str)return false;const [x,y]=viewport.convertToViewportPoint(i.transform[4],i.transform[5]);return x>=r.box[0]-2&&x<r.box[2]&&y>=r.box[1]&&y<=r.box[3]+1;});let joined='',previous=null;for(const item of parts){const value=item.str==='\u0000'?(ligatures[(item.width/item.transform[0]).toFixed(6)]||'�'):item.str;if(previous){const newline=Math.abs(item.transform[5]-previous.transform[5])>Math.max(item.height,previous.height)*.45;const gap=item.transform[4]-(previous.transform[4]+previous.width);if(newline||gap>1.1)joined+=' ';}joined+=value;previous=item;}result.push(joined.replace(/\s+/g,' ').trim());}return result.join(' ');}
export async function renderRegion(container,regions,textView=false){container.replaceChildren();const text=await regionText(regions);if(textView){container.classList.add('textmode');container.textContent=text;return text;}container.classList.remove('textmode');for(const r of regions){const p=await getPage(r.page,r.book);const scale=2;const [x0,y0,x1,y1]=r.box;const canvas=document.createElement('canvas');canvas.width=Math.ceil((x1-x0)*scale);canvas.height=Math.ceil((y1-y0)*scale);canvas.className='pdfregion';canvas.setAttribute('aria-hidden','true');const context=canvas.getContext('2d');await p.render({canvasContext:context,viewport:p.getViewport({scale}),transform:[1,0,0,1,-x0*scale,-y0*scale],background:'rgb(255,255,255)'}).promise;container.append(canvas);}const sr=document.createElement('span');sr.className='sr-only';sr.textContent=text;container.append(sr);return text;}
export function clearPDF(){for(const pdf of documents.values())pdf.destroy();documents.clear();pageCache.clear();textCache.clear();}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('mse250-local-book',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function storedPDF(value,book=1){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files',value===undefined?'readonly':'readwrite');const store=tx.objectStore('files');const r=value===undefined?store.get('book'+book):value===null?store.delete('book'+book):store.put(value,'book'+book);let result;r.onsuccess=()=>{result=r.result};tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)};});}
